owner: alchemyrpg
repo: upptime

sites:
  - name: App
    url: https://app.alchemyrpg.com
  - name: Marketing Site
    url: https://alchemyrpg.com
  - name: Gameplay API
    url: $SERVICE_GRAPHQL
  - name: Universe API
    url: $SERVICE_UNIVERSE
  - name: Marketplace API
    url: $SERVICE_MARKETPLACE
  - name: Notes API
    url: $SERVICE_NOTES
  - name: Analytics API
    url: $SERVICE_ANALYTICS

status-website:
  cname: status.alchemyrpg.com
  logoUrl: https://app.alchemyrpg.com/favicon-120.png
  theme: night
  name: Alchemy Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
assignees:
  - ioveracker

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
