owner: alchemyrpg
repo: upptime

sites:
   - name: App
     url: https://app.alchemyrpg.com
     icon: https://app.alchemyrpg.com/favicon-120.png
   - name: RTC API
     url: https://journal2.alchemyrpg.com/health
     icon: https://app.alchemyrpg.com/favicon-120.png
   - name: API
     url: https://api2.alchemyrpg.com/health
     icon: https://app.alchemyrpg.com/favicon-120.png
   - name: Marketing Site
     url: https://alchemyrpg.com
     icon: https://app.alchemyrpg.com/favicon-120.png

status-website:
  cname: status.alchemyrpg.com
  logoUrl: https://app.alchemyrpg.com/favicon-120.png
  favicon: https://app.alchemyrpg.com/favicon-120.png
  theme: night
  name: Alchemy Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
assignees:
  - ioveracker
 
# https://crontab.guru 
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
